spring:
  application:
    name: HW2.3
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
